"""
FastAPI application entrypoint.

Run: uvicorn app.main:app --reload --port 8000
Docs: http://localhost:8000/docs (auto-generated by FastAPI)
"""

from datetime import datetime, timezone
import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes import router

app = FastAPI(title="OrbitalAid API", version="0.1.0")

# ── CORS ──────────────────────────────────────────────────────────────────────
# Pull allowed origins from env (comma-separated) so Render / Vercel URLs
# can be injected without touching code.
default_origins = ["http://localhost:3000"]
env_origins = [o.strip() for o in os.getenv("CORS_ORIGINS", "").split(",") if o.strip()]
allow_origins = env_origins or default_origins

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    # Also allow any Vercel preview URL for this project
    allow_origin_regex=r"https://new-orbitalaid.*\.vercel\.app",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/")
def root():
    return {"status": "ok", "service": "OrbitalAid API"}


@app.get("/health")
def health():
    """Lightweight health-check used by Render and the frontend SystemHealth page."""
    from app.db import DATABASE_URL
    db_type = "postgresql" if "postgresql" in DATABASE_URL or "postgres" in DATABASE_URL else "sqlite"
    return {
        "status": "healthy",
        "environment": os.getenv("ENVIRONMENT", "development"),
        "database": db_type,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }